name: publish docker image on github 

on:
  workflow_dispatch:
    branches:
      - main
    paths: "backend/**"
    inputs:
      Version:
        description: 'Set image version'
        required: true
        default: 'latest'

defaults:
  run:
    working-directory: backend

jobs:
  publish-coding-challenge-image:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup node 16
      uses: actions/setup-node@v2
      with:
        node-version: 16.x
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Build and pushing the app challenge Docker image
      run: |
        docker build . --build-arg GITREV=${{ github.sha }} --tag ghcr.io/fbiedka/app-challenge:${{ github.event.inputs.version }}
        docker push ghcr.io/fbiedka/app-challenge:${{ github.event.inputs.version }}
